class Order:
    estimated_finished_commission: str
    product_detail_url: str
    estimated_paid_commission: str
    product_count: int
    order_number: str
    is_hot_product: str
    parent_order_number: str
    product_main_image_url: str
    order_status: str
    category_id: int
    settled_currency: str
    product_id: int
    order_type: str
    tracking_id: str
    created_time: str
    finished_time: str
    completed_settlement_time: str
    paid_time: str
    is_new_buyer: str
    sub_order_id: str
    custom_parameters: str
    ship_to_country: str
    product_title: str
    incentive_commission_rate: str
    new_buyer_bonus_commission: str
    estimated_incentive_paid_commission: str
    is_affiliate_product: str
    paid_amount: str
    effect_detail_status: str
    estimated_incentive_finished_commission: str
    commission_rate: str
    finished_amount: str
    order_platform: str
    order_id: str
