from aliexpress.top.api.rest.AliexpressAffiliateFeaturedpromoGetRequest import AliexpressAffiliateFeaturedpromoGetRequest
from aliexpress.top.api.rest.AliexpressAffiliateOrderGetRequest import AliexpressAffiliateOrderGetRequest
from aliexpress.top.api.rest.AliexpressAffiliateProductQueryRequest import AliexpressAffiliateProductQueryRequest
from aliexpress.top.api.rest.AliexpressAffiliateFeaturedpromoProductsGetRequest import AliexpressAffiliateFeaturedpromoProductsGetRequest
from aliexpress.top.api.rest.AliexpressAffiliateOrderListRequest import AliexpressAffiliateOrderListRequest
from aliexpress.top.api.rest.AliexpressAffiliateProductdetailGetRequest import AliexpressAffiliateProductdetailGetRequest
from aliexpress.top.api.rest.AliexpressAffiliateLinkGenerateRequest import AliexpressAffiliateLinkGenerateRequest
from aliexpress.top.api.rest.AliexpressAffiliateCategoryGetRequest import AliexpressAffiliateCategoryGetRequest
