from top.api.rest.AliexpressAffiliateFeaturedpromoGetRequest import AliexpressAffiliateFeaturedpromoGetRequest
from top.api.rest.AliexpressAffiliateOrderGetRequest import AliexpressAffiliateOrderGetRequest
from top.api.rest.AliexpressAffiliateProductQueryRequest import AliexpressAffiliateProductQueryRequest
from top.api.rest.AliexpressAffiliateFeaturedpromoProductsGetRequest import AliexpressAffiliateFeaturedpromoProductsGetRequest
from top.api.rest.AliexpressAffiliateOrderListRequest import AliexpressAffiliateOrderListRequest
from top.api.rest.AliexpressAffiliateProductdetailGetRequest import AliexpressAffiliateProductdetailGetRequest
from top.api.rest.AliexpressAffiliateLinkGenerateRequest import AliexpressAffiliateLinkGenerateRequest
from top.api.rest.AliexpressAffiliateCategoryGetRequest import AliexpressAffiliateCategoryGetRequest
